name: Frontend
on:
  push:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: print app.js content
        run: |
          echo Hello Im a step
          cat src/frontend/app.js
          
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: node src/frontend/app.js
        
